//! Literal keyword tokens in Dynare 7.2's DYNARE_STATEMENT lexer state.
//! Source: preprocessor 991946e9, src/DynareFlex.ll. INITIAL-only commands
//! (such as `steady`, `check`, and `resid`) remain IDENTIFIER in this state.

pub(super) fn keyword_token(word: &str) -> Option<String> {
    let word = word.to_ascii_lowercase();
    if !KEYWORDS.split_ascii_whitespace().any(|known| known == word) {
        return None;
    }
    Some(match word.as_str() {
        "domain" => "DOMAINN".to_string(),
        "filter_particle_diagnostics" => "FILTER_PARTICLE_DIAGNOSTICS_STATUS".to_string(),
        "particle_filtering" => "OCCBIN_PARTICLE_STATUS".to_string(),
        "posterior_importance_sampling" => "POSTERIOR_IMPORTANCE_SAMPLING_STATUS".to_string(),
        "nan" => "NAN_CONSTANT".to_string(),
        "inf" => "INF_CONSTANT".to_string(),
        _ => word.to_ascii_uppercase(),
    })
}

const KEYWORDS: &str = "
aband abs acos acosh adaptive_mh_draws add_flags add_libs add_tiny_number_to_cholesky
additional_optimizer_steps advanced aim aim_solver allow_nonfinite_values alpha alpha_rmse
alpha2_redform alpha2_rmse alpha2_stab amisanotristani analytic_derivation
analytic_derivation_mode analytic_jacobian analytic_standard_errors analytical_girf aoa apband
ar asin asinh atan atanh auxiliary_model_name auxname balanced_growth_test_tol bandpass_filter
bartlett_kernel_lag bayesian_irf beta block block_diagonal_lu block_diagonal_lu_maxlu
block_diagonal_lu_nlu block_diagonal_lu_nperiods block_diagonal_lu_relu block_dynamic
block_static bounded_shock_support bounds brooks_gelman_plotrows burnin bvar_prior_decay
bvar_prior_flat bvar_prior_lambda bvar_prior_mu bvar_prior_omega bvar_prior_tau bvar_prior_train
bvar_replic bytecode calibration calibration_max_iter calibration_target_equations
calibration_tolf calibration_verbosity cbrt chain check_jacobian_singularity checks_via_subsets
cms cnum coefficients coefficients_prior_hyperparameters colormap compiler conditional
conditional_likelihood conditional_variance_decomposition conf_sig consider_all_endogenous
consider_all_endogenous_and_auxiliary consider_only_observed constant constant_simulation_length
constants contemp_reduced_form contemporaneous_correlation controlled_varexo
convergence_ending_value convergence_increment_value convergence_starting_value corr cos cosh
cova_compute cpf_weights cross_restrictions cubature cutoff cycle_reduction data_obs_nbr
datafile dd default deflator detail_plot diff differentiate_forward_vars diffuse_filter
diffuse_kalman_tol dirichlet dirname discount discretionary_tol distribution_approximation dl
domain doubling dr dr_cycle_reduction_maxiter dr_cycle_reduction_tol dr_display_tol
dr_logarithmic_reduction_maxiter dr_logarithmic_reduction_tol drop dsge_var dsge_varlag
dummy_obs duration emas_drop emas_girf emas_max_iter emas_tolf endogenous_prior
endogenous_terminal_period endval_steady endval_steady_nocheck epilogue eps eq_cms eq_ms eqtags
equations erf erfc error_band_percentiles estimate_initial_states_endogenous_prior exp
expectation expression false fast_kalman_filter fast_realtime fig fig_name file file_tag
filename filter_algorithm filter_covariance filter_decomposition
filter_init_periods_using_particles filter_particle_diagnostics
filter_particle_diagnostics_graph_periods filter_particle_diagnostics_nograph
filter_particle_draw_states_from_empirical_density filter_particle_initial_state_ergodic_simul
filter_particle_number_of_particles filter_particle_number_of_shocks_per_particle
filter_particle_state_draws filter_particle_state_importance_sampling_logpost_crit_threshold
filter_particle_state_importance_sampling_pkf_init
filter_particle_state_importance_sampling_slice_burnin
filter_particle_state_importance_sampling_slice_override_iteration
filter_particle_use_pkf_updated_state_threshold filter_step_ahead filter_use_relaxation
filtered_probabilities filtered_theoretical_moments_grid filtered_vars final_subperiod
final_year first_deriv_provided first_iter_lu first_obs first_simulation_period fixed_point
flat_prior flip foreband forecast forecast_type forward_check_every forward_max_iter forward_tol
forward_verbosity free_parameters freq frequentist_smoother fsolve_options function
function_convergence_criterion gamma generic geweke_interval gmm gmres_restart graph
graph_format grid_nbr growth growth_factor gsa_sample_file gsig2_lmdm hessian heterogeneity
heteroskedastic_filter homotopy_exclude_varexo homotopy_force_continue
homotopy_initial_step_size homotopy_linearization_fallback
homotopy_marginal_linearization_fallback homotopy_max_completion_share homotopy_min_step_size
homotopy_mode homotopy_step_size_increase_success_count homotopy_steps horizon hp_filter
huge_number hybrid identification identity_matrix ilptau incidence incomplete_lu indxap
indxestima indxfore indxgdls indxgforehat indxgimfhat indximf indxovr indxparr indxscalesstates
inf init init_state init2shocks initial_subperiod initial_year instruments integration
interactive interval inv_gamma inv_gamma1 inv_gamma2 invars irf irf_in_percent irf_matching
irf_matching_file irf_plot_threshold irf_shocks istart_rmse iter_maxit iter_tol jscale
k_order_solver kalman_algo kalman_tol kind kitagawa ksstat_redform laplace last_obs
last_simulation_period lik_init lik_only likelihood_check_ahead_periods likelihood_curb_retrench
likelihood_inversion_filter likelihood_max_check_ahead_periods likelihood_max_kalman_iterations
likelihood_maxit likelihood_periodic_solution likelihood_periods
likelihood_piecewise_kalman_filter linear linear_approximation ll lmmcp ln load_ident_files
load_mh_file load_redform load_results_after_load_mh load_rmse load_stab log log_deflator
log_growth_factor log10 logarithmic_reduction logdata loglinear logtrans_redform lower_cholesky
lyapunov lyapunov_complex_threshold lyapunov_doubling_tol lyapunov_fixed_point_tol
marginal_density markowitz max max_block_iterations max_dim_cova_group max_dim_subsets_groups
max_iterations_increment_value max_iterations_starting_value max_nrows max_number_of_stages
max_repeated_optimization_runs maxit mcmc_jumping_covariance mean median mfs mh_conf_sig mh_drop
mh_init_scale mh_init_scale_factor mh_initialize_from_previous_mcmc
mh_initialize_from_previous_mcmc_directory mh_initialize_from_previous_mcmc_prior
mh_initialize_from_previous_mcmc_record mh_jscale mh_nblocks mh_posterior_mode_estimation
mh_recover mh_replic mh_tune_guess mh_tune_jscale min minimal_solving_periods mle_mode mode
mode_check mode_check_neighbourhood_size mode_check_number_of_points mode_check_symmetric_plots
mode_compute mode_file model_name modifiedharmonicmean mom_method moments_varendo montecarlo
monthly morris morris_nliv morris_ntra multinomial murrayjonesparslow name namendo namexo
namlagendo nan nargs ncms ncsk neighborhood_width ninv nlags no_bayesian_prior no_create_init
no_error_bands no_homotopy no_identification_minimal no_identification_moments
no_identification_reducedform no_identification_spectrum no_identification_strength
no_init_estimation_check_first_obs no_posterior_kernel_density no_static nobs nocheck noconstant
nocorr nodecomposition nodiagnostic nodisplay nofunctions nograph nomodelsummary nomoments
non_zero none nonlinear_filter_initialization noprint normal normalize_jacobians normcdf normpdf
nsam nstates nstd number_of_lags number_of_large_perturbations number_of_particles
number_of_posterior_draws_after_perturbation number_of_quadrature_nodes number_of_regimes
number_of_small_perturbations one_sided_hp_filter opt_algo optim options order outfile
output_file_tag outvars parallel_local_files parameter_convergence_criterion parameter_set
parameter_uncertainty parameters partial_information particle_filter_options particle_filtering
pdf penalized_estimator perfect period periods pfilt_rmse planner_discount
planner_discount_latex_name plot_end_date plot_init_date plot_priors posterior_graph
posterior_importance_sampling posterior_importance_sampling_filter
posterior_importance_sampling_orig_dname posterior_importance_sampling_orig_filter
posterior_importance_sampling_orig_fname posterior_importance_sampling_sub_draws
posterior_max_subsample_draws posterior_mean posterior_median posterior_mode posterior_nograph
posterior_sampler_options posterior_sampling_method ppost pprior preconditioner
predetermined_variables prefilter presample print prior prior_mc prior_mean prior_mode
prior_range prior_trunc prior_variance proposal_approximation proposal_distribution
proposal_draws proposal_lower_bound proposal_type proposal_upper_bound pruning pvalue_corr
pvalue_ks q_diag qoq quarterly qz_criterium qz_zero_threshold raftery_lewis_diagnostics
raftery_lewis_qrs random_function_convergence_criterion random_parameter_convergence_criterion
real_pseudo_forecast real_time_smoothed realtime redform regime regimes relative_irf replic
resampling resampling_method resampling_threshold rescale_prediction_error_covariance residual
restriction_fname restrictions rmse robust_lin_solve sampling_draws save_draws save_realtime
schur_vec_tol screen_shocks se_tolx second_deriv_provided seed selected_variables_only series
shape shift shock_draws shocks_per_parameter sign silent_optimizer sims_zha simul
simul_check_ahead_periods simul_curb_retrench simul_debug simul_max_check_ahead_periods
simul_maxit simul_periodic_solution simul_periodic_solution_strict
simul_periodic_solution_threshold simul_periods simul_replic simul_reset_check_ahead_periods
simul_reset_regime_in_new_period simulation_file_tag simulation_method simulation_multiple sin
sinh skewed_kalman_mvnlogcdf skewed_kalman_prune_tol skewed_kalman_rank_deficiency_transform smm
smooth smoothed_state_uncertainty smoother smoother_check_ahead_periods smoother_curb_retrench
smoother_debug smoother_first_period_occbin_update smoother_inversion_filter
smoother_max_check_ahead_periods smoother_max_number_of_iterations smoother_maxit
smoother_periodic_solution smoother_periods smoother_piecewise_kalman_filter smoother_plot
smoother_redux solve_algo solver_periods sparse specification spectral_density sqrt
square_root_solver stab stack_solve_algo static_mfs std stdev steady_markowitz steady_maxit
steady_solve_algo steady_state steady_tolf steady_tolx steadystate stoch_simul stratified stroud
structural sub_draws subsamples substitute_flags substitute_libs systematic tan tanh taper_steps
targets tensor_gaussian_quadrature tex thinning_factor threshold_redform
time_iteration_early_stopping time_iteration_learning_rate time_iteration_max_iter
time_iteration_solver_factor time_iteration_solver_max_iter time_iteration_solver_stop_on_error
time_iteration_solver_tolf time_iteration_solver_tolx time_iteration_tol
time_iteration_verbosity time_shift tlindx tlnumber tol_deriv tol_rank tol_sv tolf tolx tree
true truncate truncation_horizon type unconditional uniform unscented updated_covariance
upper_cholesky use_dll use_first_order_solution use_mean_center use_pct
use_penalized_objective_for_hessian use_shock_groups
use_univariate_filters_if_singularity_is_detected
use_univariate_smoother_if_singularity_is_detected useautocorr var var_rmse varexo varexo_det
varexobs variable variance variances varobs verbose vintage vlist vlistlog vlistper weibull
weighting_matrix weighting_matrix_scaling_factor with_epilogue write_equation_tags write_xls
xls_range xls_sheet yoy
";
